CREATE TYPE "PuestoTipo" AS ENUM (
  'GERENTE_TIENDA','ASESOR_VENTAS','COORDINADOR_COMPRAS','JEFE_ALMACEN',
  'COMMUNITY_MANAGER','PRACTICANTE_MARKETING','ANALISTA_RRHH','CONTADOR',
  'PRACTICANTE_CONTABILIDAD','OPERADOR_SERVICIO_CLIENTE','AUXILIAR_TIENDA',
  'AGENTE_SEGURIDAD_TIENDA','SUPERVISOR_SEGURIDAD','AGENTE_SEGURIDAD_ALMACEN'
);
CREATE TYPE "TurnoPreferido" AS ENUM ('MANANA','TARDE','AMBOS');
CREATE TYPE "ModalidadTrabajo" AS ENUM ('FULLTIME','PARTTIME');

ALTER TABLE "Vacante" ADD COLUMN "puesto" TEXT;
ALTER TABLE "Vacante" ADD COLUMN "turnoPreferido" TEXT NOT NULL DEFAULT 'AMBOS';
UPDATE "Vacante" SET "puesto" = CASE
  WHEN "area"='VENTAS' THEN 'ASESOR_VENTAS'
  WHEN "area"='CAJA'   THEN 'AUXILIAR_TIENDA'
  WHEN "area"='ALMACEN'THEN 'JEFE_ALMACEN'
  WHEN "area"='VISUAL' THEN 'COMMUNITY_MANAGER'
  ELSE 'ASESOR_VENTAS' END;
ALTER TABLE "Vacante" ALTER COLUMN "puesto" TYPE "PuestoTipo" USING "puesto"::"PuestoTipo";
ALTER TABLE "Vacante" ALTER COLUMN "puesto" SET NOT NULL;
ALTER TABLE "Vacante" ALTER COLUMN "turnoPreferido" TYPE "TurnoPreferido" USING "turnoPreferido"::"TurnoPreferido";
ALTER TABLE "Vacante" DROP COLUMN "area";
ALTER TABLE "Vacante" DROP COLUMN "turno";
DROP TYPE "AreaVacante";

ALTER TABLE "Disponibilidad" ADD COLUMN "modalidad" "ModalidadTrabajo" NOT NULL DEFAULT 'PARTTIME';
ALTER TABLE "Disponibilidad" ALTER COLUMN "modalidad" DROP DEFAULT;
ALTER TABLE "Disponibilidad" DROP COLUMN "turnoNoche";
ALTER TABLE "Disponibilidad" DROP COLUMN "finesDeSemanaDispo";
ALTER TABLE "Disponibilidad" DROP COLUMN "horasSemanales";
