export const PREGUNTAS = [
  { id: 1,  texto: 'Disfruto interactuar con personas y ayudarlas a encontrar lo que buscan.' },
  { id: 2,  texto: 'Me siento cómodo/a trabajando en un ambiente de mucha interacción social.' },
  { id: 3,  texto: 'Mantengo una actitud positiva incluso cuando los clientes son exigentes.' },
  { id: 4,  texto: 'Me cuesta mantener la calma cuando hay mucha presión o afluencia de público.' },
  { id: 5,  texto: 'Para mí es importante que el cliente se vaya satisfecho, aunque eso tome más tiempo.' },
  { id: 6,  texto: 'Me adapto fácilmente a los cambios de horario o tareas inesperadas.' },
  { id: 7,  texto: 'Prefiero trabajar solo/a que coordinando con un equipo.' },
  { id: 8,  texto: 'Cuando hay mucho trabajo, apoyo a mis compañeros aunque no sea mi área.' },
  { id: 9,  texto: 'Me resulta difícil pedir ayuda cuando no sé cómo hacer algo.' },
  { id: 10, texto: 'He trabajado antes en equipos con ritmo acelerado y lo manejo bien.' },
  { id: 11, texto: 'Llego puntualmente a mis compromisos laborales y personales.' },
  { id: 12, texto: 'Si cometo un error, lo reconozco y busco corregirlo de inmediato.' },
  { id: 13, texto: 'Me comprometo con los horarios acordados, incluyendo fines de semana si es necesario.' },
  { id: 14, texto: 'Cuando una tarea me aburre, me cuesta mantener el mismo nivel de esfuerzo.' },
  { id: 15, texto: 'Me interesa el mundo de la moda y me actualizo sobre tendencias.' },
  { id: 16, texto: 'Entiendo que en retail el aspecto y la presentación personal influyen en la atención.' },
  { id: 17, texto: 'Estaría dispuesto/a a aprender sobre los productos que vende la tienda.' },
  { id: 18, texto: 'Me motiva trabajar en un ambiente dinámico donde cada día es diferente.' },
];
